version: '3.7'

services:
  mongdodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'admin'
      MONGO_INITDB_ROOT_PASSWORD: 'admin'
      MONGO_INITDB_DATABASE: 'NotificationDatabase'
    expose:
      - 27017
  mysqldb:
    image: mysql:latest
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: 'postDB'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.2

    environment:
      KEYCLOAK_ADMIN: 'admin'
      KEYCLOAK_ADMIN_PASSWORD: 'admin'
    command:
      - start-dev

    ports:
      - "8069:8080"
    expose:
      - 8069


