version: '3.7'

services:
  config-server:
    image: configserver
    ports:
      - 8071:8071
    restart: on-failure

  eureka-server:
    restart: on-failure
    image: eurekaserver
    ports:
      - 8070:8070
  notification-server:
      restart: on-failure
      image: notificationservice
      ports:
        - 8091:8091
  post-server:
      restart: on-failure
      image: postservice
      ports:
        - 8090:8090


  gateway-server:
    restart: on-failure
    image: gateway-server
    ports:
      - 8092:8092

  frontend:
    image: client
    ports:
      - 4200:80

  mongdodb:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'admin'
      MONGO_INITDB_ROOT_PASSWORD: 'admin'
      MONGO_INITDB_DATABASE: 'NotificationDatabase'
    expose:
      - 27017
  mysqldb:
    image: mysql:latest
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: 'postDB'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.2

    environment:
      KEYCLOAK_ADMIN: 'admin'
      KEYCLOAK_ADMIN_PASSWORD: 'admin'
    command:
      - start-dev

    ports:
      - "8069:8080"
    expose:
      - 8069


